### ISSUE TITLE
Plugin on Nexus reported to Moderation Team.

### ISSUE THREAD

**Issue by ghost** [chazwarp923/MO2-BG3-Plugin#1]
Hey, this is just a heads up in case you don't regularly check your Nexus Mods account. Someone reported this plugin on Nexus for some reason, I have no idea why, and as a result it has been flagged for Moderation Review and cannot be downloaded. I personally believe whoever made such a report is a supercilious ass. Still, you might wish to head on over there and address any outstanding messages from Nexus' Community Managers so this mod can continue to be downloaded. I maintain a small Wabbajack modlist that uses this plugin and have decided to source it from Github here for now.

**Comment by chazwarp923** [comment]
Yeah one of the moderators pulled it down because it's not technically a mod so they said it belongs in the site category.
It's up under this [page](https://www.nexusmods.com/site/mods/807/) now

**Comment by chazwarp923** [comment]
Marking as closed
