### ISSUE TITLE
BG3SE_CONFIG support copies root files only

### ISSUE THREAD

**Issue by Yagisan** [chazwarp923/MO2-BG3-Plugin#2]
Configuration files placed into the root of the BG3SE_CONFIG folder, are only copied to `%LOCALAPPDATA%/Larian Studios/Baldur's Gate 3/Script Extender"` - however most mod config files need the entire directory tree copied. Examples are shown in the picture below.
![image](https://github.com/user-attachments/assets/2b93ebcc-debb-45b8-ac2c-54f3fcda3620)

**Comment by chazwarp923** [comment]
Fixed via #3
