### ISSUE TITLE
Support for multiple PAK files in a single mod folder?

### ISSUE THREAD

**Issue by Wash113** [chazwarp923/MO2-BG3-Plugin#7]
Hey!

So Im in the process of transferring my modlist to Patch 7 and Im running into an issue with this plugin. It would appear that the plugin only adds the first PAK file that a mod includes to the modsettings.lsx file, rather than parsing each file in the mod. As an example, take the NPC Overhaul mod. When you download the mod that has separate pak files for each character, only one of them actually gets loaded into game. The temporary solution is to create a separate mod folder in mod organizer for each pak file. Among many problems with that solution, the biggest is that when you go to update the mod you will need to manually manage each pak file back into its own individual mod. I took a look at the script and I think it should be doable by just re running some of your functions base on the number of pak files in each mod folder. But obviously that my inexperienced opinion, I tried to add it myself and failed lol. 

Thanks a ton for the plugin!

**Comment by chazwarp923** [comment]
Should be fixed via #5
